apiVersion: apps/v1
kind: Deployment
metadata:
  name: requestbin
  labels:
    app: requestbin
  annotations:
    kots.io/when: '{{repl ConfigOptionEquals "webhook_run_requestbin" "1"}}'
spec:
  selector:
    matchLabels:
      app: requestbin
  template:
    metadata:
      labels:
        app: requestbin
    spec:
      containers:
        - name: requestbin
          image: weshigbee/requestbin
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: requestbin
  labels:
    app: requestbin
  annotations:
    kots.io/when: '{{repl and (not IsKurl) (ConfigOptionEquals "webhook_run_requestbin" "1") }}'
spec:
  type: ClusterIP
  ports:
    - port: 8000
  selector:
    app: requestbin

---
apiVersion: v1
kind: Service
metadata:
  name: requestbin
  labels:
    app: requestbin
  annotations:
    kots.io/when: '{{repl and (IsKurl) (ConfigOptionEquals "webhook_run_requestbin" "1") }}'
spec:
  type: NodePort
  ports:
    - port: 8000
      nodePort: 8000
  selector:
    app: requestbin
