apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: mongodb-mtools
spec:
  title: Mongo MTools Demo
  icon: https://webassets.mongodb.com/_com_assets/cms/anomalies-6vjficq3z4.svg
  statusInformers:
    - deployment/mongodb
  ports:
    - serviceName: "mongodb"
      servicePort: 27017
      localPort: 27017
      applicationUrl: "http://mongodb"
