apiVersion: troubleshoot.replicated.com/v1beta1
kind: Collector
metadata:
  name: collector-sample
spec:
  collectors:
    # root@docker-desktop:/# mongo --eval "db.adminCommand('ping')" --host 35.223.46.118:27017
    # MongoDB shell version v4.0.16
    # connecting to: mongodb://35.223.46.118:27017/?gssapiServiceName=mongodb
    # Implicit session: session { "id" : UUID("720d5785-8971-4cd8-86b6-f2f4d44c5ceb") }
    # MongoDB server version: 4.2.3
    # WARNING: shell and server versions do not match
    # { "ok" : 1 }
    - run:
        collectorName: mongo-ping
        namespace: repl{{ Namespace }}
        image: dexhorthy/mongo-shell-example
        command: ["mongo"]
        args: ["--eval", "--db.adminCommand('ping')", "--host", "mongodb:27017"]
        timeout: 5s
