apiVersion: troubleshoot.replicated.com/v1beta1
kind: Collector
metadata:
  name: collector-sample
spec:
  collectors:
    - logs:
        selector:
          - app=nginx-hardcoded-ns
        namespace: hardcoded
